name: "tempotech"

services:
  db:
    image: mysql:8.0
    container_name: car-mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_SCHEMA}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PWD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  car-agent-network:
    driver: bridge

volumes:
  mysql_data: