-- MySQL Script generated by MySQL Workbench
-- Sun 10 Aug 2025 04:40:54 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`engine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`engine` ;

CREATE TABLE IF NOT EXISTS `mydb`.`engine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `compression_rate` VARCHAR(10) NULL,
  `total_cc` INT NULL,
  `aspiration` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transmission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transmission` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transmission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gearbox_type` VARCHAR(20) NOT NULL,
  `gears_qtde` INT NULL,
  `traction` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manufacturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`manufacturer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`manufacturer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`car` ;

CREATE TABLE IF NOT EXISTS `mydb`.`car` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `engine_id` INT NOT NULL,
  `transmission_id` INT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `name` VARCHAR(80) NULL,
  `version` VARCHAR(80) NULL,
  `year` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_car_engine_idx` (`engine_id` ASC) VISIBLE,
  INDEX `fk_car_transmission1_idx` (`transmission_id` ASC) VISIBLE,
  INDEX `fk_car_manufacturer1_idx` (`manufacturer_id` ASC) VISIBLE,
  CONSTRAINT `fk_car_engine`
    FOREIGN KEY (`engine_id`)
    REFERENCES `mydb`.`engine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_transmission1`
    FOREIGN KEY (`transmission_id`)
    REFERENCES `mydb`.`transmission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_manufacturer1`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `mydb`.`manufacturer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`equipment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`equipment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(50) NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  `is_standard` TINYINT NOT NULL,
  `is_optional` TINYINT NOT NULL,
  `car_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipment_car1_idx` (`car_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_car1`
    FOREIGN KEY (`car_id`)
    REFERENCES `mydb`.`car` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`car_specs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`car_specs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`car_specs` (
  `id` INT NOT NULL,
  `car_id` INT NOT NULL,
  `gas` VARCHAR(50) NULL,
  `config` VARCHAR(45) NULL,
  `doors` INT NULL,
  `spaces` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_car_specs_car1_idx` (`car_id` ASC) VISIBLE,
  CONSTRAINT `fk_car_specs_car1`
    FOREIGN KEY (`car_id`)
    REFERENCES `mydb`.`car` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`engine_specs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`engine_specs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`engine_specs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `engine_id` INT NOT NULL,
  `gas_type` VARCHAR(45) NULL,
  `max_hp` INT NULL,
  `max_hp_rpm` INT NULL,
  `max_torque` INT NULL,
  `max_torque_rpm` INT NULL,
  `torque_unit_measure` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_engine_specs_engine1_idx` (`engine_id` ASC) VISIBLE,
  CONSTRAINT `fk_engine_specs_engine1`
    FOREIGN KEY (`engine_id`)
    REFERENCES `mydb`.`engine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
